import type { CardDefinition, CardId } from './types'

export const HARMONY_TARGET: Record<number, number> = {
  3: 9,
  4: 8,
  5: 7,
  6: 6,
}

export const CARDS: Record<CardId, CardDefinition> = {
  'student-president': {
    id: 'student-president',
    name: '学生会长',
    shortName: '会长',
    point: 3,
    faction: 'good',
    priority: 4,
    ability: '开局时，持有学生会长的玩家声明身份并成为起始玩家。发动后无额外效果。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/student-president.webp',
  },
  'health-committee': {
    id: 'health-committee',
    name: '保健委员',
    shortName: '保健',
    point: 1,
    faction: 'good',
    priority: 4,
    ability: '从另一名玩家面前取回 1 张已发动的非保健委员牌，加入手牌。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/health-committee.webp',
  },
  'library-committee': {
    id: 'library-committee',
    name: '图书委员',
    shortName: '图书',
    point: 1,
    faction: 'good',
    priority: 4,
    ability: '秘密查看调和区内的全部卡牌，不改变顺序。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/library-committee.webp',
  },
  'discipline-committee': {
    id: 'discipline-committee',
    name: '风纪委员',
    shortName: '风纪',
    point: 1,
    faction: 'good',
    priority: 4,
    ability: '秘密查看 1 名其他玩家的全部手牌。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/discipline-committee.webp',
  },
  'young-lady': {
    id: 'young-lady',
    name: '大小姐',
    shortName: '大小姐',
    point: 1,
    faction: 'good',
    priority: 4,
    ability: '随机抽取另一名玩家 1 张手牌，再从自己手中选择 1 张背面交还；可以返还刚抽到的牌。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/young-lady.webp',
  },
  'news-club': {
    id: 'news-club',
    name: '新闻部',
    shortName: '新闻',
    point: 1,
    faction: 'good',
    priority: 4,
    ability: '所有仍在行动的玩家各选 1 张手牌，同时传给顺时针方向的下一位行动玩家。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/news-club.webp',
  },
  'class-representative': {
    id: 'class-representative',
    name: '班级委员',
    shortName: '班委',
    point: 2,
    faction: 'good',
    priority: 4,
    ability: '选择 1 名仍在行动的玩家，双方各自秘密选 1 张手牌进行交换。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/class-representative.webp',
  },
  'honor-student': {
    id: 'honor-student',
    name: '优等生',
    shortName: '优等',
    point: 2,
    faction: 'good',
    priority: 4,
    ability: '除自己外全员闭眼，犯人持有者必须示意；外星人持有者可以选择冒充犯人。',
    victory: '调和成功时，与其他善方身份一同获胜。',
    image: '/images/cards/honor-student.webp',
  },
  criminal: {
    id: 'criminal',
    name: '犯人',
    shortName: '犯人',
    point: 0,
    faction: 'criminal',
    priority: 3,
    ability: '不能作为发动、调和或质疑主动使用，但可以被其他角色能力移动或交换。',
    victory: '犯人未被监禁时，犯人与共犯一同获胜。',
    image: '/images/cards/criminal.webp',
  },
  accomplice: {
    id: 'accomplice',
    name: '共犯',
    shortName: '共犯',
    point: 0,
    faction: 'criminal',
    priority: 3,
    ability: '将任意玩家面前的 1 张质疑牌移动到另一名玩家面前。',
    victory: '犯人未被监禁时，与犯人一同获胜。',
    image: '/images/cards/accomplice.webp',
  },
  alien: {
    id: 'alien',
    name: '外星人',
    shortName: '外星人',
    point: -1,
    faction: 'neutral',
    priority: 1,
    ability: '优等生查验时可以冒充犯人示意；发动后无额外效果，作为暗牌时会降低对应点数。',
    victory: '自己成为最高质疑值的嫌犯且并非全员并列时，独自获胜。',
    image: '/images/cards/alien.webp',
  },
  infected: {
    id: 'infected',
    name: '感染者',
    shortName: '感染者',
    point: 0,
    faction: 'neutral',
    priority: 2,
    ability: '若此牌到自己的下回合开始仍留在已发动区，从调和区秘密取回 1 张牌，再继续行动。',
    victory: '调和失败时，独自获胜。',
    image: '/images/cards/infected.webp',
  },
  'go-home-club': {
    id: 'go-home-club',
    name: '归宅部',
    shortName: '归宅',
    point: 0,
    faction: 'neutral',
    priority: 5,
    ability: '用自己 1 张手牌与调和区内 1 张未知牌交换。',
    victory: '更高优先级均无人满足时，所有归宅部身份获胜。',
    image: '/images/cards/go-home-club.webp',
  },
}

export const GOOD_CARD_IDS = (Object.values(CARDS) as CardDefinition[])
  .filter((card) => card.faction === 'good')
  .map((card) => card.id)

export const DECK_COUNTS: Record<number, Partial<Record<CardId, number>>> = {
  3: {
    'student-president': 1,
    'health-committee': 2,
    'library-committee': 2,
    'discipline-committee': 1,
    'young-lady': 2,
    'news-club': 2,
    'class-representative': 2,
    'honor-student': 1,
    criminal: 1,
    alien: 1,
    infected: 1,
    'go-home-club': 2,
  },
  4: {
    'student-president': 1,
    'health-committee': 2,
    'library-committee': 2,
    'discipline-committee': 2,
    'young-lady': 3,
    'news-club': 3,
    'class-representative': 2,
    'honor-student': 2,
    criminal: 1,
    accomplice: 1,
    alien: 1,
    infected: 1,
    'go-home-club': 3,
  },
  5: {
    'student-president': 1,
    'health-committee': 2,
    'library-committee': 3,
    'discipline-committee': 2,
    'young-lady': 3,
    'news-club': 3,
    'class-representative': 2,
    'honor-student': 2,
    criminal: 1,
    accomplice: 1,
    alien: 1,
    infected: 1,
    'go-home-club': 3,
  },
  6: {
    'student-president': 1,
    'health-committee': 2,
    'library-committee': 2,
    'discipline-committee': 2,
    'young-lady': 3,
    'news-club': 3,
    'class-representative': 2,
    'honor-student': 2,
    criminal: 1,
    accomplice: 1,
    alien: 1,
    infected: 1,
    'go-home-club': 3,
  },
}
